--
-- PostgreSQL database dump for "BURMALDA" shop
--

-- Создание таблицы Categories
CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL
);

-- Создание таблицы Products
CREATE TABLE IF NOT EXISTS "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Description" text,
    "Price" decimal NOT NULL,
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories"("Id") ON DELETE CASCADE
);

-- Создание таблицы Orders
CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerName" text NOT NULL,
    "CustomerEmail" text NOT NULL,
    "CustomerPhone" text NOT NULL,
    "DeliveryAddress" text NOT NULL,
    "OrderDate" timestamptz NOT NULL,
    "TotalAmount" decimal NOT NULL
);

-- Создание таблицы OrderItems
CREATE TABLE IF NOT EXISTS "OrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" decimal NOT NULL,
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products"("Id") ON DELETE CASCADE
);

-- Индексы
CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON "Products" ("CategoryId");
CREATE INDEX IF NOT EXISTS "IX_Orders_OrderDate" ON "Orders" ("OrderDate");
CREATE INDEX IF NOT EXISTS "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
CREATE INDEX IF NOT EXISTS "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");

-- Начальные данные: категории
INSERT INTO "Categories" ("Id", "Name") VALUES
(1, 'Процессоры'),
(2, 'Видеокарты'),
(3, 'Оперативная память'),
(4, 'Материнские платы')
ON CONFLICT ("Id") DO NOTHING;

-- Начальные данные: товары
INSERT INTO "Products" ("Id", "Name", "Description", "Price", "ImageUrl", "Stock", "CategoryId") VALUES
(1, 'Intel Core i7-13700K', '16 ядер, до 5.4 ГГц', 38500, 'https://gansor.ru/image/cache/catalog/cpu/intel/740bb6c5f8b83f8786439d6a5f63b583.png', 10, 1),
(2, 'AMD Ryzen 9 7950X', '16 ядер, 5.7 ГГц', 55000, 'https://avatars.mds.yandex.net/get-mpic/15258748/2a00000197c56c2f14633014ff7df6e87232/orig', 5, 1),
(3, 'NVIDIA RTX 4070 Ti', '12GB GDDR6X', 82000, 'https://i.ebayimg.com/images/g/dk0AAOSwIGBkWOzp/s-l1600.png', 7, 2),
(4, 'AMD Radeon RX 7900 XT', '20GB GDDR6', 91000, 'https://ir.ozone.ru/s3/multimedia-g/6817709284.jpg', 3, 2),
(5, 'Kingston 32GB DDR5', '5600MHz', 42500, 'https://main-cdn.sbermegamarket.ru/big2/hlr-system/-42/374/966/122/153/600009586171b1.jpeg', 15, 3),
(6, 'MSI PRO B760-P', 'LGA1700, DDR5', 14500, 'https://main-cdn.sbermegamarket.ru/big2/hlr-system/-42/374/966/122/153/600009586171b1.jpeg', 8, 4)
ON CONFLICT ("Id") DO NOTHING;

-- Сброс последовательностей (чтобы следующие ID продолжали правильно)
SELECT setval('"Categories_Id_seq"', (SELECT MAX("Id") FROM "Categories"));
SELECT setval('"Products_Id_seq"', (SELECT MAX("Id") FROM "Products"));
SELECT setval('"Orders_Id_seq"', (SELECT COALESCE(MAX("Id"), 1) FROM "Orders"));
SELECT setval('"OrderItems_Id_seq"', (SELECT COALESCE(MAX("Id"), 1) FROM "OrderItems"));